package com.bank.daos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import com.bank.pojos.Account;
import com.bank.utils.ConnectionFactory;


public class AccountDao implements Dao<Account, Integer> {

	
	@Override
	public Account create(Account accountObj) {

		try (Connection conn = ConnectionFactory.getInstance().getConnection()) {
			
			// 	Set autocommit to false
			conn.setAutoCommit(false);
			
			
			// 	Insert query
			String insert_statement = "insert into P0_ACCOUNTS " +
										"(ACCOUNT_NUMBER, USERID, STATUS) " +
										"values " +
										"( ?, ?, ? )";
			
			// 	Autogenerated keys to represent from db insert
			String[] autogen_keys = {"ACCOUNTID"};
			
			
			// 	Prepare insert statement
			PreparedStatement ps = conn.prepareStatement(insert_statement, autogen_keys);
			
			
			// 	Prepare insert statement with getter values from Account object, 
			//	as prepared statement parameters
			ps.setString(1, accountObj.getAccount_number());
			ps.setInt(2, accountObj.getUserid());
			ps.setString(3, accountObj.getStatus());
			
			
			//	Execute insert statement and return number of rows added.
			int rowsInserted = ps.executeUpdate();
			
			if (rowsInserted > 0) {
				
				//	Get the results (such as ACCOUNTID pk) from database after insert statement was executed.
				ResultSet rs = ps.getGeneratedKeys();
				
				//	Loop over result(s) from insert.
				while ( rs.next() ) {
					
					//	Set id attribute of Person object
					accountObj.setAccountid(rs.getInt(1));
					
				}
				
				conn.commit();
				
			} // end if
					
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return accountObj;
		
	}

	@Override
	public Account read(Integer id) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Account update(Account obj) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void delete(Account obj) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public List<Account> findAll() {
		// TODO Auto-generated method stub
		return null;
	}

}
