package com.bank.daos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import com.bank.pojos.User;
import com.bank.utils.ConnectionFactory;


public class UserDao implements Dao<User, Integer> {

	
	@Override
	public User create(User userObj) {

		try (Connection conn = ConnectionFactory.getInstance().getConnection()) {
			
			// 	Set autocommit to false
			conn.setAutoCommit(false);
			
			
			// 	Insert query
			String insert_statement = "insert into P0_USERS " +
									  "(USERNAME, PASSWORD, EMAIL, PERSONID) " +
									  "values " +
									  "( ?, ?, ?, ? )";
			
			
			// 	Autogenerated keys to represent from db insert
			String[] autogen_keys = {"USERID"};
			
			
			// 	Prepare insert statement
			PreparedStatement ps = conn.prepareStatement(insert_statement, autogen_keys);
			
			
			// 	Prepare insert statement with getter values from User object, 
			//	as prepared statement parameters
			ps.setString(1, userObj.getUsername());
			ps.setString(2, userObj.getPassword());
			ps.setString(3, userObj.getEmail());
			ps.setInt(4, userObj.getPersonid());		// Can this be passed as null... ? Would be fine too
			
			
			//	Execute insert statement and return number of rows added.
			int rowsInserted = ps.executeUpdate();
			
			if (rowsInserted > 0) {
				
				//	Get the results (such as USERID pk) from database after insert statement was executed.
				ResultSet rs = ps.getGeneratedKeys();
				
				//	Loop over result(s) from insert.
				while ( rs.next() ) {
					
					//	Set id attribute of Person object
					userObj.setUserid(rs.getInt(1));
					
				}
				
				conn.commit();
				
			} // end if
					
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return userObj;
		
	}

	@Override
	public User read(Integer id) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public User update(User obj) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void delete(User obj) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public List<User> findAll() {
		// TODO Auto-generated method stub
		return null;
	}
	
	public int[] login(String p_username, String p_password) {
		
		int _success = 0;
		int _userid = 0;
		
		try ( Connection conn = ConnectionFactory.getInstance().getConnection() ) {
			
			//	Create this as a function 
			//	(which will accepet un and pw in paramenters
			//	 and one out parameter returning the userid) 
			//	and return count(1).
			String select_query = "select count(1) as success, p0_users.userid from p0_accounts " +
								  "inner join p0_users on p0_accounts.userid = p0_users.userid " +
								  "where upper(p0_users.username) = upper(?) " +
								  "and upper(p0_users.password) = upper(?) " + 
								  "group by p0_users.userid";
			
			PreparedStatement ps = conn.prepareStatement(select_query);
			ps.setString(1, p_username);
			ps.setString(2, p_password);
			
			ResultSet rs = ps.executeQuery();

			while ( rs.next() ) {
				
				_success = rs.getInt(1);
				_userid = rs.getInt(2);
				
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		int[] _myArr = {_success, _userid};
		return _myArr;
	}

}
