/*
DATA MANIPULATION LANGUAGE
CRUD
INSERT, SELECT, UPDATE, DELETE
*/

SELECT * FROM ARTIST;

INSERT INTO ARTIST (ARTISTID, NAME)
VALUES(276, 'Beyonce');

INSERT INTO ARTIST (ARTISTID, NAME)
VALUES(277, 'Outkast');

UPDATE ARTIST
SET NAME = 'NOT OUTKAST'
WHERE ARTISTID = 277;

DELETE FROM ARTIST WHERE ARTISTID BETWEEN 1 AND 10;

SELECT * FROM ARTIST;
DELETE FROM ARTIST WHERE ARTISTID > 275;
SAVEPOINT SP1;

-- TCL
commit;
-- always commit upon successful db transactions
--