drop user oneAdmin CASCADE;

create user oneAdmin
identified by onePassword;
grant connect to oneAdmin;
grant resource to oneAdmin;

conn oneAdmin/onePassword

Create Table ERS_REIMBURSEMENT
(
  REIMB_ID NUMBER PRIMARY KEY,
  REIMB_AMOUNT NUMBER NOT NULL,
  REIMB_SUBMITTED TIMESTAMP,
  REIMB_RESOLVED TIMESTAMP,
  REIMB_DESCRIPTION VARCHAR2(250),
  REIMB_RECEIPT BLOB,
  REIMB_AUTHOR NUMBER NOT NULL,
  REIMB_RESOLVER NUMBER,
  REIMB_STATUS_ID NUMBER NOT NULL,
  REIMB_TYPE_ID NUMBER NOT NULL,
  CONSTRAINT ERS_USERS_FK_AUTH FOREIGN KEY(REIMB_AUTHOR)
      REFERENCES ERS_USERS(ERS_USERS_ID),
  CONSTRAINT ERS_USERS_FK_RESLVR FOREIGN KEY(REIMB_RESOLVER)
      REFERENCES ERS_USERS(ERS_USERS_ID),
  CONSTRAINT ERS_REIMBURSEMENT_STATUS_FK FOREIGN KEY(REIMB_STATUS_ID)
      REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID),
  CONSTRAINT ERS_REIMBURSEMENT_TYPE_FK FOREIGN KEY(REIMB_TYPE_ID)
      REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID)
);

CREATE TABLE ERS_USERS
(
  ERS_USERS_ID NUMBER PRIMARY KEY,
  ERS_USERNAME VARCHAR2(50) UNIQUE NOT NULL,
  ERS_PASSWORD VARCHAR2(50) NOT NULL,
  USER_FIRST_NAME VARCHAR2(100) NOT NULL,
  USER_LAST_NAME VARCHAR2(100) NOT NULL,
  USER_EMAIL VARCHAR2(150) UNIQUE NOT NULL,
  USER_ROLE_ID NUMBER NOT NULL,
  CONSTRAINT USER_ROLES_FK FOREIGN KEY(USER_ROLE_ID)
      REFERENCES ERS_USER_ROLES(ERS_USER_ROLE_ID)
);

CREATE TABLE ERS_REIMBURSEMENT_STATUS
(
  REIMB_STATUS_ID NUMBER PRIMARY KEY,
  REIMB_STATUS VARCHAR2(10) NOT NULL
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE
(
  REIMB_TYPE_ID NUMBER PRIMARY KEY,
  REIMB_TYPE VARCHAR2(10) NOT NULL
);

CREATE TABLE ERS_USER_ROLES
(
  ERS_USER_ROLE_ID NUMBER PRIMARY KEY,
  USER_ROLE VARCHAR2(10) NOT NULL
);

CREATE SEQUENCE reimb_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE user_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER reimb_seq_trig
BEFORE INSERT ON ERS_REIMBURSEMENT
FOR EACH ROW
BEGIN
  SELECT  reimb_seq.nextVal INTO :new.REIMB_ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER user_seq_trig
BEFORE INSERT ON ERS_USERS
FOR EACH ROW
BEGIN
  SELECT user_seq.nextVal INTO :new.ERS_USERS_ID FROM dual;
END;
/

commit;
exit;