package model;

public class BankAccount {
	private int account_id;
	private int user_id;
	private int balance;
	private String account_type;
	
	
	
	public BankAccount() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	/* constructor no.1
	 * 
	 * beginning , 
	 * user only input the userid, balance and accounttype
	 * then, we save this new Bankaccount into sql, 
	 * accountId would be auto generated by DB sequence
	 * then , it will have 4 fields in sql DB 
	 * then , i will have to take these 4 fields and put into 
	 * constructor no.2
	 * 
	 * */
	public BankAccount(int user_id, int balance, String account_type) {
		super();
		this.user_id = user_id;
		this.balance = balance;
		this.account_type = account_type;
	}
	
	
	/*
	 *  constructor no.2
	 * user only input the userid, balance and accounttype
	 * */
	public BankAccount(int account_id, int user_id, int balance, String account_type) {
		super();
		this.account_id = account_id;
		this.user_id = user_id;
		this.balance = balance;
		this.account_type = account_type;
	}
	
	
	public int getAccount_id() {
		return account_id;
	}
	public void setAccount_id(int account_id) {
		this.account_id = account_id;
	}
	public int getUser_id() {
		return user_id;
	}
	public void setUser_id(int user_id) {
		this.user_id = user_id;
	}
	public int getBalance() {
		return balance;
	}
	public void setBalance(int balance) {
		this.balance = balance;
	}
	public String getAccount_type() {
		return account_type;
	}
	public void setAccount_type(String account_type) {
		this.account_type = account_type;
	}
	@Override
	public String toString() {
		return "BankAccount [account_id=" + account_id + ", user_id=" + user_id + ", balance=" + balance
				+ ", account_type=" + account_type + "]";
	}
	
	
}
