/*
    If in local
        create user demo 
        identified by demo;
        grant connect to demo;
        grant resource to demo;
    If in AWS
        Use (same)current user
*/

-- BOOKSTORE DDL SCRIPT

CREATE TABLE B_GENRE
(
    GENRE_ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(256) UNIQUE NOT NULL
);

CREATE TABLE B_AUTHOR
(
    AUTHOR_ID NUMBER(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50),
    BIOGRAPHY VARCHAR2(1000)
);

CREATE TABLE BOOK 
(
    BOOK_ID NUMBER(10) PRIMARY KEY,
    ISBN VARCHAR2(10) UNIQUE NOT NULL,
    TITLE VARCHAR2(256) NOT NULL,
    PRICE NUMBER(6, 2) NOT NULL,
    GENRE_ID NUMBER(10),
    AUTHOR_ID NUMBER(10),
    -- AUTHOR_ID NUMBER(10) |FOREIGN KEY?
    --CONSTRAINT FK_BOOK_GENRE 
    FOREIGN KEY (GENRE_ID) REFERENCES B_GENRE(GENRE_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES B_AUTHOR(AUTHOR_ID)
);

CREATE TABLE BOOK_AUTHOR
(
    BOOK_ID NUMBER(10),
    AUTHOR_ID NUMBER(10),
    PRIMARY KEY (BOOK_ID, AUTHOR_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES B_AUTHOR(AUTHOR_ID)
);

--CONSTRAINT "PK_INVOICELINE" PRIMARY KEY ("INVOICELINEID")

----------



